name: Release Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Build binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o ice-kube-linux
          GOOS=darwin GOARCH=amd64 go build -o ice-kube-macos
          GOOS=windows GOARCH=amd64 go build -o ice-kube.exe

      - name: Upload binaries to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ice-kube-linux
            ice-kube-macos
            ice-kube.exe
